import type { AppRole } from "./roles";
import { ROLES } from "./roles";

export type SidebarItem = {
  icon: string;
  label: string;
  path: string;
  description: string;
  roles: AppRole[];
};

export const sidebarItems: SidebarItem[] = [
  {
    icon: "DB",
    label: "Dashboard",
    path: "/dashboard/home",
    description: "High-level performance and activity overview.",
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    icon: "AN",
    label: "Analytics",
    path: "/dashboard/analytics",
    description: "Live ERP charts for fees, attendance, and performance.",
    roles: [ROLES.ADMIN, ROLES.STAFF],
  },
  {
    icon: "ST",
    label: "Students",
    path: "/dashboard/students",
    description: "Student records and classroom allocations.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "SF",
    label: "Staff",
    path: "/dashboard/staff",
    description: "Faculty assignments and coordination details.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "CL",
    label: "Classes",
    path: "/dashboard/classes",
    description: "Class sections, rooms, capacity, and coordinator links.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "SB",
    label: "Subjects",
    path: "/dashboard/subjects",
    description: "Subject catalog and academic grouping.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "TT",
    label: "Timetable",
    path: "/dashboard/timetable",
    description: "Class schedule planning and weekly structure.",
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    icon: "AT",
    label: "Attendance",
    path: "/dashboard/attendance",
    description: "Daily attendance control and record review.",
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    icon: "EX",
    label: "Exams",
    path: "/dashboard/exams",
    description: "Exam scheduling and assessment windows.",
    roles: [ROLES.ADMIN, ROLES.STAFF],
  },
  {
    icon: "RS",
    label: "Results",
    path: "/dashboard/results",
    description: "Marks, grades, and exam performance records.",
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    icon: "HD",
    label: "Holidays",
    path: "/dashboard/holidays",
    description: "School-wide holiday calendar and closures.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "AD",
    label: "Admission",
    path: "/dashboard/applicants",
    description: "Applicant pipeline and admission review.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "HR",
    label: "HR",
    path: "/dashboard/employees",
    description: "Employee records and workforce operations.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "SA",
    label: "Staff Attendance",
    path: "/dashboard/staff-attendance",
    description: "Daily HR attendance marking and monthly review.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "LV",
    label: "Leaves",
    path: "/dashboard/leaves",
    description: "Employee leave approval and tracking.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "NT",
    label: "Notifications",
    path: "/dashboard/notifications",
    description: "Leave impact alerts and coordinator actions.",
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    icon: "AC",
    label: "Accounts",
    path: "/dashboard/fees",
    description: "Fees, dues, and collection operations.",
    roles: [ROLES.ADMIN, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    icon: "SU",
    label: "Subscription",
    path: "/dashboard/subscription",
    description: "Current ERP plan, expiry, and renewal status.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "PS",
    label: "Pay Platform",
    path: "/dashboard/platform-payments",
    description: "Submit payment proof to the super admin.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "BH",
    label: "Billing History",
    path: "/dashboard/billing-history",
    description: "Track all platform payment submissions and outcomes.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "IR",
    label: "Invoices",
    path: "/dashboard/invoices",
    description: "Download invoices and receipts for the school account.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "RR",
    label: "Renewals",
    path: "/dashboard/renewal-reminders",
    description: "See renewal reminders and commercial alerts.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "PU",
    label: "Plan Upgrade",
    path: "/dashboard/plan-upgrade",
    description: "Request plan upgrades or billing-cycle changes.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "UD",
    label: "Usage",
    path: "/dashboard/usage",
    description: "Monitor storage and account consumption against limits.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "BP",
    label: "Billing Profile",
    path: "/dashboard/school-billing-profile",
    description: "Maintain school billing and finance details.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "SL",
    label: "Salary",
    path: "/dashboard/salary",
    description: "Payroll and salary release tracking.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "TR",
    label: "Transport",
    path: "/dashboard/vehicles",
    description: "Vehicle assignments and route visibility.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "RT",
    label: "Routes",
    path: "/dashboard/routes",
    description: "Transport routes and stop mapping.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "CH",
    label: "Child",
    path: "/dashboard/child",
    description: "Linked child profile for parent monitoring.",
    roles: [ROLES.PARENT],
  },
  {
    icon: "PF",
    label: "Profile",
    path: "/dashboard/profile",
    description: "Your ERP account details and identity.",
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT, ROLES.PARENT],
  },
  {
    icon: "LG",
    label: "Audit Logs",
    path: "/dashboard/audit-logs",
    description: "Review school activity by admins and staff.",
    roles: [ROLES.ADMIN],
  },
  {
    icon: "SE",
    label: "Settings",
    path: "/dashboard/settings",
    description: "Account session and workspace settings.",
    roles: [ROLES.ADMIN, ROLES.STAFF, ROLES.STUDENT, ROLES.PARENT],
  },
];
